..\bin\CarPlansParser\CarPlansParser ..\disasm\FATAL.EXE_disasm_object_3_disassembly_formatted.asm ..\WhipLib\CarPlans\F1WackPlans.h f1wack
..\bin\CarPlansParser\CarPlansParser ..\disasm\FATAL.EXE_disasm_object_3_disassembly_formatted.asm ..\WhipLib\CarPlans\AutoPlans.h xauto
..\bin\CarPlansParser\CarPlansParser ..\disasm\FATAL.EXE_disasm_object_3_disassembly_formatted.asm ..\WhipLib\CarPlans\DesilvaPlans.h xdesilva
..\bin\CarPlansParser\CarPlansParser ..\disasm\FATAL.EXE_disasm_object_3_disassembly_formatted.asm ..\WhipLib\CarPlans\PulsePlans.h xpulse
..\bin\CarPlansParser\CarPlansParser ..\disasm\FATAL.EXE_disasm_object_3_disassembly_formatted.asm ..\WhipLib\CarPlans\GlobalPlans.h xglobal
..\bin\CarPlansParser\CarPlansParser ..\disasm\FATAL.EXE_disasm_object_3_disassembly_formatted.asm ..\WhipLib\CarPlans\MillionPlans.h xmillion
..\bin\CarPlansParser\CarPlansParser ..\disasm\FATAL.EXE_disasm_object_3_disassembly_formatted.asm ..\WhipLib\CarPlans\MissionPlans.h xmission
..\bin\CarPlansParser\CarPlansParser ..\disasm\FATAL.EXE_disasm_object_3_disassembly_formatted.asm ..\WhipLib\CarPlans\ZizinPlans.h xzizin
..\bin\CarPlansParser\CarPlansParser ..\disasm\FATAL.EXE_disasm_object_3_disassembly_formatted.asm ..\WhipLib\CarPlans\ReisePlans.h xreise

..\bin\CarPlansParser\CarPlansParser ..\disasm\FATAL.EXE_disasm_object_3_disassembly_formatted.asm ..\WhipLib\SignPlans\TowerPlans.h tower
..\bin\CarPlansParser\CarPlansParser ..\disasm\FATAL.EXE_disasm_object_3_disassembly_formatted.asm ..\WhipLib\SignPlans\Tower2Plans.h tower2
..\bin\CarPlansParser\CarPlansParser ..\disasm\FATAL.EXE_disasm_object_3_disassembly_formatted.asm ..\WhipLib\SignPlans\Sign01Plans.h sign01
..\bin\CarPlansParser\CarPlansParser ..\disasm\FATAL.EXE_disasm_object_3_disassembly_formatted.asm ..\WhipLib\SignPlans\Sign02Plans.h sign02
..\bin\CarPlansParser\CarPlansParser ..\disasm\FATAL.EXE_disasm_object_3_disassembly_formatted.asm ..\WhipLib\SignPlans\BuildPlans.h build
..\bin\CarPlansParser\CarPlansParser ..\disasm\FATAL.EXE_disasm_object_3_disassembly_formatted.asm ..\WhipLib\SignPlans\Build1Plans.h build1
..\bin\CarPlansParser\CarPlansParser ..\disasm\FATAL.EXE_disasm_object_3_disassembly_formatted.asm ..\WhipLib\SignPlans\Build2Plans.h build2
..\bin\CarPlansParser\CarPlansParser ..\disasm\FATAL.EXE_disasm_object_3_disassembly_formatted.asm ..\WhipLib\SignPlans\Build3Plans.h build3
..\bin\CarPlansParser\CarPlansParser ..\disasm\FATAL.EXE_disasm_object_3_disassembly_formatted.asm ..\WhipLib\SignPlans\HeelbarPlans.h heelbar
..\bin\CarPlansParser\CarPlansParser ..\disasm\FATAL.EXE_disasm_object_3_disassembly_formatted.asm ..\WhipLib\SignPlans\BalloonPlans.h balloon
..\bin\CarPlansParser\CarPlansParser ..\disasm\FATAL.EXE_disasm_object_3_disassembly_formatted.asm ..\WhipLib\SignPlans\Balloon2Plans.h balloon2
..\bin\CarPlansParser\CarPlansParser ..\disasm\FATAL.EXE_disasm_object_3_disassembly_formatted.asm ..\WhipLib\SignPlans\TreePlans.h tree
..\bin\CarPlansParser\CarPlansParser ..\disasm\FATAL.EXE_disasm_object_3_disassembly_formatted.asm ..\WhipLib\SignPlans\AdvertPlans.h advert
..\bin\CarPlansParser\CarPlansParser ..\disasm\FATAL.EXE_disasm_object_3_disassembly_formatted.asm ..\WhipLib\SignPlans\Advert2Plans.h advert2
..\bin\CarPlansParser\CarPlansParser ..\disasm\FATAL.EXE_disasm_object_3_disassembly_formatted.asm ..\WhipLib\SignPlans\Advert3Plans.h advert3
..\bin\CarPlansParser\CarPlansParser ..\disasm\FATAL.EXE_disasm_object_3_disassembly_formatted.asm ..\WhipLib\SignPlans\QuadBldPlans.h quadbld
..\bin\CarPlansParser\CarPlansParser ..\disasm\FATAL.EXE_disasm_object_3_disassembly_formatted.asm ..\WhipLib\SignPlans\Bld0Plans.h bld0